apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymenthooks.apps.mx.com
  namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
  group: apps.mx.com
  names:
    kind: DeploymentHook
    plural: deploymenthooks # If not specified, Kubernetes would assume the plural is "DeploymentHooks"
    singular: deploymenthook
    shortNames:
      - deployhook
      - deploymenthook
      - deployhooks
      - deploymenthooks
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["debounceSeconds", "selector", "containers"]
              properties:
                # Amount of time to debounce in case multiple deployments match the same name
                debounceSeconds:
                  type: integer

                # Selector for a deployments labels
                selector:
                  type: object
                  required: ["labels"]
                  properties:
                    labels:
                      type: object
                      additionalProperties: true
                # Container overrides
                containers:
                  type: array
                  items:
                    type: object
                    required: ["name", "command"]
                    properties:
                      # Name of container to overrides
                      name:
                        type: string
                      # New command name of the container
                      command:
                        type: array
                        items:
                          type: string
