---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nginx-test
  namespace: docbot-test
data:
  TEST_CONFIG: "12345"
  TEST_KEY_YOLO: brolo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: docbot-test
  labels:
    app: nginx
    apps.mx.com/deploymenthook: finished
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        envFrom:
          - configMapRef:
              name: config-nginx-test
        ports:
        - containerPort: 80
