---
apiVersion: v1
kind: PodTemplate
metadata:
  name: nginx-pod-template
  namespace: docbot-test
  labels:
    app: nginx
template:
  metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      command:
        - "sh"
        - "-c"
        - |
          echo "Doing some work..."
          echo "Still working on it..."
          echo "Done!"
      envFrom:
        - configMapRef:
            name: config-nginx-test
      ports:
      - containerPort: 80
